from unicodedata import unidata_version


PRECIO= 300 
precio= print(PRECIO)
CANTIDAD= 3
cantidad=print(CANTIDAD)
PRECIO_UNITARIO=PRECIO/CANTIDAD

PRECIO= 900
precio= print(PRECIO)
CANTIDAD= 10
cantidad=print(CANTIDAD)
PRECIO_UNITARIO=PRECIO/CANTIDAD

PRECIO= 120
precio= print(PRECIO)
CANTIDAD= 50
cantidad=print(CANTIDAD)
PRECIO_UNITARIO=PRECIO/CANTIDAD

PRECIO= 250
precio= print(PRECIO)
CANTIDAD= 100
cantidad=print(CANTIDAD)
PRECIO_UNITARIO=PRECIO/CANTIDAD